---
- name: Create a folder on the desktop, update apt cache, and install tree
  hosts: 
    - 192.168.88.113
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Display OS release
      debug:
        var: ansible_distribution + " " + ansible_distribution_version
      when: "'Ubuntu' in ansible_distribution"
      
    - name: Get list of installed packages
      command: dpkg-query -W
      register: installed_packages

    - name: Display list of installed packages
      debug:
        var: installed_packages.stdout_lines

