---
- name: Create a folder on the desktop, update apt cache, and install tree
  hosts: 192.168.88.22
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
         
  
          