---
- name: Configure Static IP On Ubuntu PC
  hosts: 192.168.88.212
  become: yes
  tasks:
    - name: Set static IP address
      ansible.builtin.lineinfile:
        path: /etc/netplan/01-netcfg.yaml
        line: |
          network:
            version: 2
            renderer: networkd
            ethernets:
              ens18:
                addresses: ['192.168.88.211/24']
                gateway4: '192.168.88.1'
                nameservers:
                  addresses: [192.168.88.195]

    - name: Apply Netplan Configuration
      ansible.builtin.command:
        cmd: sudo netplan apply
      register: netplan_result
      ignore_errors: yes  
