---
- name: Configure Static IP On Ubuntu PC
  hosts: 192.168.88.211
  become: yes
  tasks:
    - name: Set static IP address
      ansible.builtin.lineinfile:
        path: /etc/netplan/00-installer-config.yaml 
        line: |
          network:
            version: 2
            renderer: networkd
            ethernets:
              ens18:
                addresses: ['192.168.88.212/24']
                gateway4: '192.168.88.1'
                nameservers:
                  addresses: [192.168.88.195]
      notify: Apply Netplan Configuration

  handlers:
    - name: Apply Netplan Configuration
      ansible.builtin.command:
        cmd: sudo netplan apply
      failed_when: "'Error' in result.stderr"  # Fail only if 'Error' is present in the command's stderr
