---
- name: Configure Static IP Address on Ubuntu 
  hosts: 192.168.88.120
  become: yes
  tasks:
    - name: Configure Netplan
      blockinfile:
        path: /etc/netplan/00-installer-config.yaml
        marker: "# {mark} ANSIBLE MANAGED BLOCK - Static IP Configuration"
        block: |
          network:
            version: 2
            ethernets:
              enp1s0:
                dhcp4: false
                addresses:
                  - 192.168.88.25/24
                gateway4: 192.168.88.1
                nameservers:
                  addresses: [192.168.88.195]
              enp0s3:
                dhcp4: false
                addresses:
                  - 192.168.88.120/24
                gateway4: 192.168.88.1
                nameservers:
                  addresses: [192.168.88.195]
      when: "'enp1s0' in ansible_interfaces or 'enp0s3' in ansible_interfaces"

    - name: Apply Netplan Changes
      command: netplan apply

    - name: Restart Networking
      service:
        name: networking
        state: restarted
